//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckinPortal.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCountryMaster
    {
        public int CountryMasterID { get; set; }
        public string Country_Full_name { get; set; }
        public string Country_3Char_code { get; set; }
        public string Country_2Char_code { get; set; }
    }
}
