//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckinPortal.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEventTrackingDetail
    {
        public int EventTrackingID { get; set; }
        public Nullable<int> ReservationID { get; set; }
        public Nullable<int> EventSubModuleID { get; set; }
        public string StatusType { get; set; }
    
        public virtual tbEventSubModuleMaster tbEventSubModuleMaster { get; set; }
        public virtual tbReservationDetail tbReservationDetail { get; set; }
    }
}
