//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckinPortal.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOperaPaymentTypeCodeWeb
    {
        public int ID { get; set; }
        public string OperaPaymentTypeCode { get; set; }
        public string VendorPaymentTypeCode { get; set; }
    }
}
