//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckinPortal.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPaymentAdditionalInfo
    {
        public int PaymentAddInforID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public string KeyHeader { get; set; }
        public string KeyValue { get; set; }
    }
}
