//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckinPortal.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbReservationDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbReservationDetail()
        {
            this.tbEventTrackingDetails = new HashSet<tbEventTrackingDetail>();
        }
    
        public int ReservationDetailID { get; set; }
        public string ReservationNameID { get; set; }
        public string ReservationNumber { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<int> Adultcount { get; set; }
        public Nullable<int> Childcount { get; set; }
        public string MembershipNo { get; set; }
        public string MembershipType { get; set; }
        public Nullable<bool> IsDepositAvailable { get; set; }
        public Nullable<bool> IsCardDetailPresent { get; set; }
        public Nullable<bool> IsSaavyPaid { get; set; }
        public Nullable<System.DateTime> DataInsertedDate { get; set; }
        public Nullable<System.DateTime> Dataupdateddate { get; set; }
        public Nullable<bool> IsLocallySynced { get; set; }
        public Nullable<System.DateTime> LocallySyncedDateTime { get; set; }
        public Nullable<bool> IsPreCheckedInPMS { get; set; }
        public string FlightNo { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public string ReservationSource { get; set; }
        public byte[] SignatureImage { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<bool> IsMemberShipEnrolled { get; set; }
        public string RoomType { get; set; }
        public string RoomTypeDescription { get; set; }
        public Nullable<bool> IsPreCheckedOutPMS { get; set; }
        public Nullable<bool> EcomPaymentStatus { get; set; }
        public Nullable<bool> IsCheckOutFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEventTrackingDetail> tbEventTrackingDetails { get; set; }
    }
}
