//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckinPortal.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRequestDetail
    {
        public int ReqDetailID { get; set; }
        public Nullable<int> ReqTypeMasterID { get; set; }
        public Nullable<int> ReservationDetailID { get; set; }
        public Nullable<bool> ReqStatus { get; set; }
        public Nullable<System.DateTime> ReqCreatedDateTime { get; set; }
        public Nullable<System.DateTime> ReqUpdatedDateTime { get; set; }
        public string ReqUserComment { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
