//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckinPortal.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRoomTypeMapping
    {
        public int RoomTypeMappingID { get; set; }
        public Nullable<int> RoomTypeID { get; set; }
        public Nullable<int> PackageTypeID { get; set; }
    }
}
